Update featured page
Sileo/featuredpage pull request #7
Opened 2022-03-31 19:51 UTC by flowerible

- Added more recent tweaks
- Updated existing tweaks with their proper repo

2022-04-01 13:30 UTC, m1stadev requested changes

2022-04-01 13:30 UTC, m1stadev commented on featured-ipad-src.json
> +               "url":"https://featuredpage.getsileo.app/banners/com.smokin1337.satellite.jng",
Typo, but nevertheless please have the banners in JPG format.

2022-04-01 13:30 UTC, m1stadev commented on featured-iphone-src.json
> +                       "packageAuthor":"initWithFrame",
Extra space here?

2022-04-01 13:30 UTC, m1stadev commented on featured-ipad-src.json
>                 "title":"Snapper 2",
Please change this package to something else.

2022-04-01 13:30 UTC, m1stadev commented on featured-ipad-src.json
>                 "title":"Elysian",
Please change this package to something else.

2022-04-01 13:30 UTC, m1stadev commented on featured-ipad-src.json
>                       "packageName":"Groups",
Please change this package.

2022-04-02 07:05 UTC, elihwyma approved these changes
lgtm

2022-04-03 04:06 UTC, merged